### ISSUE TITLE
All Latency Tests have No Results

### ISSUE THREAD

**Issue by matt30000** [blrchen/azure-speed-test#104]
All the latency tests have a large cursor instead of results in the display. 

![Results Failure](https://user-images.githubusercontent.com/79994243/109839135-6e7bf000-7c0c-11eb-82b8-f7dd0b3f9b3c.jpg)

**Comment by matt30000** [comment]
If possible please fix quickly, thank you.

**Comment by blrchen** [comment]
I am fixing this right now.

**Comment by blrchen** [comment]
Thanks for raising this up. This is fixed. Root cause is the subscription hosts Azure storage accounts running out of MSDN monthly $150 budget. It seems someone repeatedly download blobs and generate a $200 billing for bandwidth on 4th March.

**Comment by matt30000** [comment]
Thank you!
