### ISSUE TITLE
FR: New Azure Region GA - US West 3

### ISSUE THREAD

**Issue by iamGavinJ** [blrchen/azure-speed-test#120]
Hi @blairch, US West 3 was announced today.

https://azure.microsoft.com/en-gb/blog/expanding-cloud-services-microsoft-launches-its-sustainable-datacenter-region-in-arizona/

When you have time would you mind adding it to your latency test?

**Comment by blrchen** [comment]
Thanks for letting me know, West US 3 has been enabled.
