### ISSUE TITLE
Add North Italy region

### ISSUE THREAD

**Issue by louij2** [blrchen/azure-speed-test#122]
Hi,

I am trying to troubleshoot some issues with North Italy DC that's in Milan but have noticed that it's missing on the site.
It would be really helpful if you could add it.

Thanks

**Comment by blrchen** [comment]
Per Azure's official site, https://azure.microsoft.com/en-us/global-infrastructure/geographies/#geographies North Italy region status is coming soon. I can add it when this region become general available later.

**Comment by rnobili1** [comment]
Hello. I think that now North Italy its UP&Running. Could you add it? Thanks

**Comment by Matusa69** [comment]
Since North Italy is up&running please add it on the application, we have a lot local italian customers plan to use it. Thx

**Comment by blrchen** [comment]
North Italy has now been added. Please let us know if you experience any issues.
