### ISSUE TITLE
Google AD is hiding part of the data sheet, causing confusion

### ISSUE THREAD

**Issue by recolic** [blrchen/azure-speed-test#149]
While running a speedtest on <https://www.azurespeed.com/Azure/Latency>, the AD on the bottom of the page would prevent some data from showing up. 
It's confusing and some users would think "these datacenters are not responding". I request to move the AD to the right side, left side or top side. Or add a white area at the bottom of the page to prevent them from stacking. 

![image](https://user-images.githubusercontent.com/19610256/160747790-c541cd05-4422-44f3-8ab2-031a19c803c3.png)

**Comment by blrchen** [comment]
Thanks for @recolic contributing. Fix has been applied to latency page, will try to port the fix to other pages or find a solution to fix this globally and then close this issue.
