### ISSUE TITLE
Large File Upload to UK South/West failing

### ISSUE THREAD

**Issue by ghost** [blrchen/azure-speed-test#151]
Tried uploaded a couple of file sizes and change the block size and threads but hangs about 3rd of the way.

The upload test works fine

**Comment by ben-thomas-insight** [comment]
![image](https://user-images.githubusercontent.com/97441380/161065106-50f27dd5-3d74-4c45-acca-6b524a8bcf08.png)
![image](https://user-images.githubusercontent.com/97441380/161065151-477d2f57-4e09-4185-83be-e7bdbe797528.png)

**Comment by blrchen** [comment]
Thanks for reporting this bug,  I guess one workaround might be F5 refresh page and re-test.

**Comment by ben-thomas-insight** [comment]
I attempted the refresh and another browser (Chrome) vs Edge, still hangs about the 3rd of the way.

Changed the file size to 512MB and it works fine

![image](https://user-images.githubusercontent.com/97441380/161232390-e9f624a9-d6b4-4aa2-9824-74596052183a.png)

Not sure if this helps or if 512MB is the maximum

**Comment by blrchen** [comment]
The `Large File Upload Speed Test` page now supports files larger than 512MB. Have verified this by uploading a 1GB test file to UK South and confirmed upload speed test completed successfully.

![image](https://github.com/user-attachments/assets/b0c83cc0-0848-4c2c-af96-3dc9f446cac5)
