### ISSUE TITLE
Download Speed Tests show XML Error

### ISSUE THREAD

**Issue by ajtuk** [blrchen/azure-speed-test#155]
Trying to use the Download speed test. Instead of the usual 100MB BIN file downloading, the browser shows an XML error.

<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:ee37f896-301e-0075-1ee4-b6f2bd000000 Time:2022-08-23T11:38:59.4976923Z</Message>
<AuthenticationErrorDetail>Signed expiry time [Mon, 22 Aug 2022 09:37:10 GMT] must be after signed start time [Tue, 23 Aug 2022 11:38:59 GMT]</AuthenticationErrorDetail>
</Error>

**Comment by randalhansen** [comment]
I have this same issue as well.

**Comment by tlmartins** [comment]
I having the same now.

**Comment by blrchen** [comment]
@ajtuk @randalhansen @tlmartins thanks for raising this up. This has been caused by a recent nameserver change, I rolled back the change to mitigate this issue.

**Comment by randalhansen** [comment]
@blrchen thanks for the quick fix.
