### ISSUE TITLE
[Feature Request] 10GB Download Test File Add

### ISSUE THREAD

**Issue by ramazansancar** [blrchen/azure-speed-test#160]
Hello, I created a Speed Test system to be a resource on my own website. I'm using Vultr files for now. However, it seems that this will not be enough in the near future. I want to use the Download files on your system, but for users with 1GBPS connection speed, 100 MB file is not enough :(

You can review:
- https://github.com/ramazansancar/nicesi-speedtest
- https://speedtest.ramazansancar.com.tr/

**Comment by blrchen** [comment]
I agree providing a 100MB file for speed testing may not be sufficient for users with a 1 GBPS connection speed to accurately gauge their internet performance. However, at this time, there is no plan to support a 10GB download file directly. One of the primary reasons for this is that hosting and serving large files, can be quite costly in terms of storage and traffic.

As an alternative, you may want to consider setting up your own hosting. This would allow you to offer a 10 GB download file to your users.
