### ISSUE TITLE
azure ip lookup broken?

### ISSUE THREAD

**Issue by eoq** [blrchen/azure-speed-test#166]
First of all great site and tools! Definately a go to for me.

Last week I noticed the Search button for Azure IP Lookup was not working. I tried again this morning with different browsers and different ips and still appears broken. 

Can you do a quick check?

Thanks
Ed

**Comment by blrchen** [comment]
Hello, @eoq , thanks for reporting this issue. I did some quick test but ip lookup just worked for me. 

## Web UI: 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1607381/217149040-4e90b88d-45a6-4c40-bcb0-5336b9913861.png">

## Web API
Access `https://www.azurespeed.com/api/ipinfo?ipAddressOrUrl=www.azurespeed.com` I can get 
```json
[{"serviceTagId":"AppService","ipAddress":"104.45.231.79","ipAddressPrefix":"104.45.231.79/32","region":"","regionId":"0","systemService":"AzureAppService","networkFeatures":"API NSG UDR FW VSE"},{"serviceTagId":"AppService.WestUS","ipAddress":"104.45.231.79","ipAddressPrefix":"104.45.231.79/32","region":"westus","regionId":"37","systemService":"AzureAppService","networkFeatures":"API NSG UDR FW"},{"serviceTagId":"AzureCloud.westus","ipAddress":"104.45.231.79","ipAddressPrefix":"104.45.224.0/19","region":"westus","regionId":"37","systemService":"","networkFeatures":"API NSG"},{"serviceTagId":"AzureCloud","ipAddress":"104.45.231.79","ipAddressPrefix":"104.45.224.0/19","region":"","regionId":"0","systemService":"","networkFeatures":"API NSG"}]
```

**Comment by eoq** [comment]
Ok. I guess I was mistaken. I was searching for an address that doesn't match Azure (for example 1.1.1.1) and it shows no indication there was no match and that threw me.  Not sure why now but using the api url is clear.
I guess ideally it would say 'Not found' or something but not a big deal.
Thanks
Ed

**Comment by blrchen** [comment]
Thanks for clarification. I agree showing "Not found" will greatly improve user experience.

**Comment by qliu95114** [comment]
i vote to show "Not Found in Azure Prefix range"
