### ISSUE TITLE
I cannot see Azure China 6 regions 

### ISSUE THREAD

**Issue by qliu95114** [blrchen/azure-speed-test#170]
There are six Azure China regions, but now this are gone! 

![image](https://github.com/blrchen/azure-speed-test/assets/17083200/b45de2df-09b1-4475-9fb2-e42ae5d185cb)

**Comment by qliu95114** [comment]
@blairch  any update?

**Comment by blrchen** [comment]
Hi @qliu95114 , sorry for the delayed response. Thank you for reporting the issue. The six regions that were mistakenly removed have now been added back.
