### ISSUE TITLE
500 Internal Server Error on IP Lookup

### ISSUE THREAD

**Issue by cv-anthony** [blrchen/azure-speed-test#172]
![Screenshot 2023-11-06 at 8 57 46 AM](https://github.com/blrchen/azure-speed-test/assets/133809856/97e27b1e-374d-4dca-b2c2-fb6d52f17d34)

API seems to be having trouble with Azure IP Lookup. Can we get this fixed soon please?

Thanks,
cv-anthony

**Comment by blrchen** [comment]
Hi @cv-anthony , 

Thanks for reporting this issue, I just fixed it - it's because a storage account mistakenly deleted during a cleanup. Could you please try again? Please let me know if you still experience any issues.

**Comment by cv-anthony** [comment]
Looks good to go. Thanks for quick fix!
