### ISSUE TITLE
https://azurespeed.com auto-reroute to https://www.azurespeed.com does not work

### ISSUE THREAD

**Issue by qliu95114** [blrchen/azure-speed-test#180]
We noticed an issue where users navigating to `https://azurespeed.com/` are not redirected to `https://www.azurespeed.com`. This is causing a CORS issue with the latency check storage.

**Comment by blrchen** [comment]
The issue was resolved by implementing a 301 redirect from <https://azurespeed.com> to <https://www.azurespeed.com>.
