### ISSUE TITLE
API providing the list of vms available with details about the size and region is not working anymore

### ISSUE THREAD

**Issue by singhimayank** [blrchen/azure-speed-test#93]
http://azurespeed.com/api/vmslugs, there used to be an API like this which had been exposed and used to return the list of all available vms with their details and region information.
This is not working now, is there any alternative for this ?

**Comment by blrchen** [comment]
Azure ratecard api has been changed a bit and I gave up maintain that api. You might want to check if this API from Azure marketplace works https://azuremarketplace.microsoft.com/api/v2.0/slugs?api-version=2017-04-24&billingregion=us
